-- Virtual Stock Trading Platform
-- PostgreSQL schema derived from Plan.md

CREATE EXTENSION IF NOT EXISTS pgcrypto;

DO $$
BEGIN
    IF NOT EXISTS (SELECT 1 FROM pg_type WHERE typname = 'order_side') THEN
        CREATE TYPE order_side AS ENUM ('BUY', 'SELL');
    END IF;

    IF NOT EXISTS (SELECT 1 FROM pg_type WHERE typname = 'order_type') THEN
        CREATE TYPE order_type AS ENUM ('MARKET');
    END IF;

    IF NOT EXISTS (SELECT 1 FROM pg_type WHERE typname = 'order_status') THEN
        CREATE TYPE order_status AS ENUM ('FILLED', 'REJECTED');
    END IF;
END
$$;

CREATE TABLE IF NOT EXISTS users (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    email VARCHAR(255) NOT NULL UNIQUE,
    username VARCHAR(100) NOT NULL UNIQUE,
    hashed_password TEXT NOT NULL,
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

CREATE TABLE IF NOT EXISTS wallets (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id BIGINT NOT NULL UNIQUE REFERENCES users (id) ON DELETE CASCADE,
    cash_balance NUMERIC(18, 2) NOT NULL DEFAULT 100000.00,
    updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    CONSTRAINT wallets_cash_balance_nonnegative CHECK (cash_balance >= 0)
);

CREATE TABLE IF NOT EXISTS stocks (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    symbol VARCHAR(20) NOT NULL UNIQUE,
    name VARCHAR(255) NOT NULL,
    current_price NUMERIC(12, 4) NOT NULL,
    previous_close NUMERIC(12, 4) NOT NULL,
    volatility NUMERIC(6, 4) NOT NULL,
    updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    CONSTRAINT stocks_current_price_positive CHECK (current_price > 0),
    CONSTRAINT stocks_previous_close_positive CHECK (previous_close > 0),
    CONSTRAINT stocks_volatility_nonnegative CHECK (volatility >= 0)
);

CREATE TABLE IF NOT EXISTS price_ticks (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    stock_id BIGINT NOT NULL REFERENCES stocks (id) ON DELETE CASCADE,
    price NUMERIC(12, 4) NOT NULL,
    timestamp TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    CONSTRAINT price_ticks_price_positive CHECK (price > 0)
);

CREATE INDEX IF NOT EXISTS idx_price_ticks_stock_timestamp
    ON price_ticks (stock_id, timestamp DESC);

CREATE TABLE IF NOT EXISTS holdings (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id BIGINT NOT NULL REFERENCES users (id) ON DELETE CASCADE,
    stock_id BIGINT NOT NULL REFERENCES stocks (id) ON DELETE CASCADE,
    quantity INTEGER NOT NULL DEFAULT 0,
    avg_cost_basis NUMERIC(12, 4) NOT NULL DEFAULT 0,
    CONSTRAINT holdings_user_stock_unique UNIQUE (user_id, stock_id),
    CONSTRAINT holdings_quantity_nonnegative CHECK (quantity >= 0),
    CONSTRAINT holdings_avg_cost_basis_nonnegative CHECK (avg_cost_basis >= 0)
);

CREATE TABLE IF NOT EXISTS orders (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id BIGINT NOT NULL REFERENCES users (id) ON DELETE CASCADE,
    stock_id BIGINT NOT NULL REFERENCES stocks (id) ON DELETE CASCADE,
    side order_side NOT NULL,
    order_type order_type NOT NULL DEFAULT 'MARKET',
    quantity INTEGER NOT NULL,
    price_at_execution NUMERIC(12, 4),
    total_value NUMERIC(18, 2),
    status order_status NOT NULL,
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    CONSTRAINT orders_quantity_positive CHECK (quantity > 0),
    CONSTRAINT orders_price_positive CHECK (price_at_execution IS NULL OR price_at_execution > 0),
    CONSTRAINT orders_total_value_nonnegative CHECK (total_value IS NULL OR total_value >= 0)
);

CREATE INDEX IF NOT EXISTS idx_orders_user_created_at
    ON orders (user_id, created_at DESC);

CREATE INDEX IF NOT EXISTS idx_orders_stock_created_at
    ON orders (stock_id, created_at DESC);